version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filedb
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/filedb?sslmode=disable
    networks:
      - app_network
    ports:
      - "8080:8080"

networks:
  app_network:
    driver: bridge
